title: Cristina Garcia
logo: /IMG_4391.jpg
description: I'm passionate about bridging biology, business, and data analytics to drive results.
theme: jekyll-theme-minimal

# Custom sidebar links
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/cristina-garcia99/
  - name: Email
    url: mailto:mcgarcia092@gmail.com
