title: Cristina Garcia
logo: CristinaG_portfolio/IMG_4391.jpg
description: I'm passionate about bridging biology, business, and data analytics to drive results. 
#show_ downloads: true             
theme: jekyll-theme-minimal
